### ISSUE TITLE
suggestions for additional transformation controls

### ISSUE THREAD

**Issue by dicook** [gammarama/intRo#28]
On the transformation panel, 

(1) it would be useful to be able to control the binwidth of the histogram. It is difficult to just the success of the transformation with a histogram with a small binwidth.

(2) Sometimes transformations are done to "linearize" the relationship between two variables. Could you add controls for this. Suggest a check box or menu for "purpose". If it is to linearize, users need to select two variables, that are then displayed as a scatterplot, and then they have control of one variable to transform.

(3) Change base of log transform to be base 2 or 10, or choose a base

**Comment by erichare** [comment]
Great suggestions! (1) and (3) should be quick and relatively easy to add. (2) might take a little bit of restructuring but is also doable.

**Comment by erichare** [comment]
I've added the binwidth, and the log transform base - I think we're going to table (2) which is going to involve more extensive changes.
